name: mini_cafe_app
description: "Firebase ile entegre Mini Cafe uygulamasÄ±"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cappuccino.png
    - assets/images/cay.png
    - assets/images/chai_latte.png
    - assets/images/tweety.png
    - assets/images/cheesecake.png
    - assets/images/ihlamur.png
    - assets/images/meyveli_pasta.png
    - assets/images/mozaik_pasta.png
    - assets/images/papatya_cayi.png
    - assets/images/profiterol.png
    - assets/images/supangle.png
    - assets/images/sutlac.png
    - assets/images/Tatli.png
    - assets/images/trilece.png
    - assets/images/turk_kahvesi.png
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700